# print('Hello World')
name= input('Enter your name:')
age = int(input('Enter your age'))
print(type(age))
# print(name)
# print(age)
print('My name is',name,'and i\'m',age, 'years old')
print(f'My name is {name} and i\'m {age} years old')